Update configure.ac for FMOD Ex
git-svn-id: svn://solarus-engine.org/solarus@243 08e91b48-8f19-0410-8fc9-9db6b7bce602

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3789,75 +3789,6 @@ fi
 # Checks for libraries.
 
 
-{ echo "$as_me:$LINENO: checking for main in -lfmodex" >&5
-echo $ECHO_N "checking for main in -lfmodex... $ECHO_C" >&6; }
-if test "${ac_cv_lib_fmodex_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lfmodex  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-
-int
-main ()
-{
-return main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_fmodex_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_fmodex_main=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_fmodex_main" >&5
-echo "${ECHO_T}$ac_cv_lib_fmodex_main" >&6; }
-if test $ac_cv_lib_fmodex_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBFMODEX 1
-_ACEOF
-
-  LIBS="-lfmodex $LIBS"
-
-else
-  { { echo "$as_me:$LINENO: error: The FMOD Ex library is missing" >&5
-echo "$as_me: error: The FMOD Ex library is missing" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
 { echo "$as_me:$LINENO: checking for IMG_Load in -lSDL_image" >&5
 echo $ECHO_N "checking for IMG_Load in -lSDL_image... $ECHO_C" >&6; }
 if test "${ac_cv_lib_SDL_image_IMG_Load+set}" = set; then
@@ -4073,6 +4004,75 @@ _ACEOF
 else
   { { echo "$as_me:$LINENO: error: The SDLmain library is missing" >&5
 echo "$as_me: error: The SDLmain library is missing" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+{ echo "$as_me:$LINENO: checking for main in -lfmodex" >&5
+echo $ECHO_N "checking for main in -lfmodex... $ECHO_C" >&6; }
+if test "${ac_cv_lib_fmodex_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lfmodex  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_fmodex_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_fmodex_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_fmodex_main" >&5
+echo "${ECHO_T}$ac_cv_lib_fmodex_main" >&6; }
+if test $ac_cv_lib_fmodex_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBFMODEX 1
+_ACEOF
+
+  LIBS="-lfmodex $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: The FMOD Ex library is missing" >&5
+echo "$as_me: error: The FMOD Ex library is missing" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5227,7 +5227,7 @@ fi
 done
 
 
-for ac_header in fmod/fmod.h
+for ac_header in fmodex/fmod.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -5368,8 +5368,8 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 _ACEOF
 
 else
-  { { echo "$as_me:$LINENO: error: The FMOD header file (fmod/fmod.h) is missing" >&5
-echo "$as_me: error: The FMOD header file (fmod/fmod.h) is missing" >&2;}
+  { { echo "$as_me:$LINENO: error: The FMOD Ex header file (fmodex/fmod.h) is missing" >&5
+echo "$as_me: error: The FMOD Ex header file (fmodex/fmod.h) is missing" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
