Use FMOD Ex instead of FMOD 3.75
git-svn-id: svn://solarus-engine.org/solarus@240 08e91b48-8f19-0410-8fc9-9db6b7bce602

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3789,13 +3789,13 @@ fi
 # Checks for libraries.
 
 
-{ echo "$as_me:$LINENO: checking for main in -lfmod" >&5
-echo $ECHO_N "checking for main in -lfmod... $ECHO_C" >&6; }
-if test "${ac_cv_lib_fmod_main+set}" = set; then
+{ echo "$as_me:$LINENO: checking for main in -lfmodex" >&5
+echo $ECHO_N "checking for main in -lfmodex... $ECHO_C" >&6; }
+if test "${ac_cv_lib_fmodex_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lfmod  $LIBS"
+LIBS="-lfmodex  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3830,30 +3830,30 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_fmod_main=yes
+  ac_cv_lib_fmodex_main=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_fmod_main=no
+	ac_cv_lib_fmodex_main=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_fmod_main" >&5
-echo "${ECHO_T}$ac_cv_lib_fmod_main" >&6; }
-if test $ac_cv_lib_fmod_main = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_fmodex_main" >&5
+echo "${ECHO_T}$ac_cv_lib_fmodex_main" >&6; }
+if test $ac_cv_lib_fmodex_main = yes; then
   cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBFMOD 1
+#define HAVE_LIBFMODEX 1
 _ACEOF
 
-  LIBS="-lfmod $LIBS"
+  LIBS="-lfmodex $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: The FMOD library is missing" >&5
-echo "$as_me: error: The FMOD library is missing" >&2;}
+  { { echo "$as_me:$LINENO: error: The FMOD Ex library is missing" >&5
+echo "$as_me: error: The FMOD Ex library is missing" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
